version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0.30"
    restart: always
    environment:
      MYSQL_DATABASE: employeemanager
      MYSQL_USER: tekane15
      MYSQL_PASSWORD: Kgodisho@15
      MYSQL_ROOT_PASSWORD: Kgodisho@15
    ports:
      - "3307:3306"
